services:
    packy.analyzer.analyzer_factory:
        class: AppBundle\Analyzer\AnalyzerFactory
    packy.analyzer.generic_analyzer:
        class: AppBundle\Analyzer\GenericAnalyzer
        arguments:
            - @packy.analyzer.analyzer_factory
    packy.repository.project:
        class: AppBundle\Repository\ProjectRepository
        arguments:
            - @doctrine.orm.entity_manager
    packy.repository.user:
        class: AppBundle\Repository\UserRepository
        arguments:
            - @doctrine.orm.entity_manager